### ISSUE TITLE
custom.entity and custom.world commands not working in RaspberryJuice

### ISSUE THREAD

**Issue by Deltaklotz** [Bigjango13/MCPI-Addons#24]
I dont know if its said somewhere, but ive tried using the custom.world and custom.entity commands to spawn entities and particles in my world, but my Spigot 1.12 server simply returned "[command] is not supported:
my python console:
```
C:\Users\delta>python3.11
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mcpi_addons.minecraft import Minecraft
>>> mc = Minecraft.create("localhost")
>>> mc.particle(-3,5,-6,"flame")
>>> mc.particle(-3,5,-6,"reddust")
Drained Data: <b'Fail'>
Last Message: <b'custom.world.particle(flame|-3.0|5.0|-6.0)'>
>>> mc.particle(-3,5,-6,"crit")
Drained Data: <b'Fail'>
Last Message: <b'custom.world.particle(reddust|-3.0|5.0|-6.0)'>
>>> mc.particle(-3,5,-6,"flame")
Drained Data: <b'Fail'>
Last Message: <b'custom.world.particle(crit|-3.0|5.0|-6.0)'>
>>> from mcpi_addons.entity import SNOWBALL
>>> mc.entity.spawn(-3,5,-6,SNOWBALL.id)
Drained Data: <b'Fail'>
Last Message: <b'custom.world.particle(flame|-3.0|5.0|-6.0)'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\delta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mcpi_addons\minecraft.py", line 127, in spawn
    self.conn.sendReceive(
  File "C:\Users\delta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mcpi_addons\connection.py", line 67, in sendReceive
    return self.receive()
           ^^^^^^^^^^^^^^
  File "C:\Users\delta\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\mcpi_addons\connection.py", line 61, in receive
    raise RequestError("%s failed" % self.lastSent.strip())
mcpi_addons.connection.RequestError: b'custom.entity.spawn(-3,5.0,-6.0,81.0,-1,0.0,0.0,0)' failed
```

and this is the erver console of my Spigot 1.12 server:
```
[01:33:25 INFO]: [RaspberryJuice] Starting input thread
[01:33:25 INFO]: [RaspberryJuice] Starting output thread!
[01:34:07 WARN]: [RaspberryJuice] custom.world.particle is not supported.
[01:34:13 WARN]: [RaspberryJuice] custom.world.particle is not supported.
[01:34:40 WARN]: [RaspberryJuice] custom.world.particle is not supported.
[01:34:52 WARN]: [RaspberryJuice] custom.world.particle is not supported.
[01:36:01 WARN]: [RaspberryJuice] custom.entity.spawn is not supported.
```
i dont know if other custom commands also have this problem, or if its just these. if its said somewhere that these commands dont work with Raspberry Juice, im sorry to have wasted your time.

**Comment by Bigjango13** [comment]
Sorry, but this isn't a bug. This is mainly for Minecraft Pi Edition. A fork of RaspberryJuice could be made to support it, so I'll keep this issue open.
